### ISSUE TITLE
Github Profile Page Update

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#10]
**Actions**:

1. Each member will have an introductory profile page on Wiki.

Some good examples (given in feedback mail):
https://github.com/bounswe/bounswe2018group3/wiki/Recep-Deniz-Aksoy
https://github.com/bounswe/bounswe2018group3/wiki/%C3%96zge-Din%C3%A7soy
https://github.com/bounswe/bounswe2018group3/wiki/Furkan-Enes-Yal%C3%A7%C4%B1n

**Deadline** : 26.02.2019, 23:59

**Comment by cerentahtasiz** [comment]
done

**Comment by yusufyuksel96** [comment]
done

**Comment by alpercakan** [comment]
done

**Comment by yusufyuksel96** [comment]
done

**Comment by ahmetyigitgedik** [comment]
Done

**Comment by furkanaydar** [comment]
Done

**Comment by ozdenali** [comment]
done
