### ISSUE TITLE
Reviewing existing project documents

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#106]
**Actions:**
1. Reviewing wiki pages for requirements, personas and user stories, mockups, diagrams project plan and communication plan

**Deadline:** 04.10.2019

**Comment by ismet-dagli** [comment]
Done collaboratively with @yilmazvolkan

**Comment by yilmazvolkan** [comment]
We understand the project structure and build some questions in order to make it more clearer with @ismet-dagli .
