### ISSUE TITLE
Revising Requirements for new participants

### ISSUE THREAD

**Issue by ismet-dagli** [bounswe/bounswe2019group8#108]
**Actions:**

1. Prepare a list of questions and clarifications to refine the requirements
2. Arrange those clarifications points in order to make a revision for requirements, mockups, designs and project plan.

**Deadline:** 26.09.2019 17.00

**Comment by ismet-dagli** [comment]
Requirements are revised with @yilmazvolkan. I point out some ambiguous details:

In Glossary
Alert	: Which criteria does create an alert according to stock, indices, etc.
Annotation: Does only trader has ability to comment both article indiviually and the comment of the user or both basic user and trader can do action?

**Comment by yilmazvolkan** [comment]
Here are my comments:

There is an uncertainty whether guest user shall see users' portfolio or not. It is not mentioned but they should see them I believe if we look the use case diagram.

Basic user in scenerio 1 buys a trading equipment however, in requirements it is said basic user has no access to those equipments. It is the only difference between trader and basic.

**Comment by sercanersoy** [comment]
Thanks for your feedbacks. I created a new issue (see #114) for the refinements and closing this one.
