### ISSUE TITLE
Meeting Notes Update 

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#11]
**Actions**:

1. Meeting 1 and Meeting 2 notes will be updated according to format described in lecture and examples.

Some good examples (given in feedback mail):
https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%236-(12.03.2018)
https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%2316-(12.12.2018)

**Deadline** : 03.03.2019

**Comment by alpercakan** [comment]
Some feedback about this from today's lecture:

1. We should write more about the details of the discussion instead of just listing their "title"s,
2. We should put deadline a little bit earliner than the sunday before the next lecture so that we have some buffer in between

**Comment by efe-onal-2016400267** [comment]
done
