### ISSUE TITLE
Standardising the Documents

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#110]
**Actions:**
1. Preparing a standard/convention for all namings, fonts, document templates etc of all kinds of documents and work items; including, but not limited to: pull requests, issues, meeting notes, personal pages and techinical documents (such as requirements)

**Deadline:** 04.10.2019

**Comment by sercanersoy** [comment]
Added template for issues.

**Comment by sercanersoy** [comment]
Added CONTRIBUTING.md file for coding guidelines.

**Comment by yilmazvolkan** [comment]
We need to look and then decide on pull request title conventions, branch naming conventions, commit titles and issue naming.

**Comment by sercanersoy** [comment]
Updated [Team Standards](https://github.com/bounswe/bounswe2019group8/wiki/Team-Standards). Feel free to open a new issue for a specific modification request to this document. Closing this issue.
