### ISSUE TITLE
Revising Mockups for new participants

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#111]
**Actions:**

1. Prepare a list of questions and clarifications to refine the mockups
2. Arrange those clarifications points in order to make a revision for requirements, mockups, designs and project plan.

**Deadline:** 26.09.2019 17.00

**Comment by ismet-dagli** [comment]
Mock-ups are revised with @yilmazvolkan. I point out some ambiguous details: 

In Scenario 1
-There is a login package for mock-up but there is no sign-up mock-up package. What does it require while signing up

In Scenario 2
-Search by price button is unnecessary. There is no alternative. What will happen when off the button? 

In Scenario 3 
-What does graph include with it? It seems unambiguous. 

In Scenario 6
-Should platform always create an alert when below the value like in 5.00 to 4.93 in USD/TL.

**Comment by yilmazvolkan** [comment]
Here are some points that are not clear for me when I analyze:

In scenario 1, the button that leads to portfolio is not clear; we can understand the "bag" icon button after analysing some mockups but initially it was not understood.

In scenario 6, i just wonder is the alert for buying or selling price because there is a gap between them and I usually set different alerts for each.

**Comment by furkanaydar** [comment]
> In scenario 6, i just wonder is the alert for buying or selling price because there is a gap between them and I usually set different alerts for each.

Changed the text in  [Scenario 6](https://github.com/bounswe/bounswe2019group8/wiki/Mockups#scenario-6-salih-okutan) a little bit to clarify the transaction.

**Comment by sercanersoy** [comment]
Thanks for your feedbacks. I am creating a new issue for the refinements and closing this one.
