### ISSUE TITLE
Revising Design for new participants

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#112]
**Actions:**

1. Prepare a list of questions and clarifications to refine the design
2. Arrange those clarifications points in order to make a revision for requirements, mockups, design and project plan.

**Deadline:** 26.09.2019 17.00

**Comment by ismet-dagli** [comment]
Done collaboratively with @yilmazvolkan and all looks good and clear.

**Comment by yilmazvolkan** [comment]
Diagrams are clear and easly comprehensible. I could see nothing to change or improve needed with @ismet-dagli
