### ISSUE TITLE
Revising Project Plan for new participants

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#113]
**Actions:**

1. Prepare a list of questions and clarifications to refine the project plan
2. Arrange those clarifications points in order to make a revision for requirements, mockups, designs and project plan.

**Deadline:** 26.09.2019 17.00

**Comment by yilmazvolkan** [comment]
Project plan is reviewed with @ismet-dagli and since current project plan doesn't contain new semester, we couldn't contribute anything new.

**Comment by ismet-dagli** [comment]
The past project plan is reviewed with @yilmazvolkan. There seems nothing causing a problem.
