### ISSUE TITLE
Updating the requirements after new members' reviews

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#114]
**Actions:**
1. Update the definition of alert in the glossary.
1. Update the definition of annotation in the glossary.
1. Update the guest user's functions.
1. Updating the basic user's functions.

**Notes:**
- This issue is created after new members' review. (See #108)
- [x] Ambiguity on the definition of alert: Which criteria does create an alert according to stock, indices, etc.
- [x] Ambiguity on the definition of annotation: Does only trader has ability to comment both article indiviually and the comment of the user or both basic user and trader can do action?
- [x] There is an uncertainty whether guest user shall see users' portfolio or not. It is not mentioned but they should see them I believe if we look the use case diagram.
- [x] Basic user in scenerio 1 buys a trading equipment however, in requirements it is said basic user has no access to those equipments. It is the only difference between trader and basic.

**Deadline:** 30.09.2019 - 23.59

**Comment by sercanersoy** [comment]
I take the action 1.

**Comment by sercanersoy** [comment]
Action 1 is done.

**Comment by efe-onal-2016400267** [comment]
I'll take action 2.

**Comment by efe-onal-2016400267** [comment]
Action 2 is done.

**Comment by alpercakan** [comment]
Taking the third one

**Comment by alpercakan** [comment]
Please add any questions you might want to ask the customer here:
https://github.com/bounswe/bounswe2019group8/wiki/Questions-for-the-Customer-Meeting-on-30-09-2019

**Comment by sercanersoy** [comment]
Opened new issue (see #118) for the action 3. Closing this issue.
