### ISSUE TITLE
Updating the mockups after new members' reviews

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#115]
**Actions:**
1. Update scenario 1.
1. Update scenario 2.
1. Update scenario 3.
1. Update scenario 6.

**Notes:**
- This issue is created after new members' review. (See #111)
- [x] For scenario 1: There is a login package for mock-up but there is no sign-up mock-up package. What does it require while signing up? Also, the button that leads to portfolio is not clear; we can understand the "bag" icon button after analysing some mockups but initially it was not understood.
- [x] For scenario 2: Search by price button is unnecessary. There is no alternative. What will happen when off the button?
- [x] For scenario 3: What does graph include with it? It seems unambiguous.
- [x] For scenario 6: Should platform always create an alert when below the value like in 5.00 to 4.93 in USD/TL. Also, I just wonder is the alert for buying or selling price because there is a gap between them and I usually set different alerts for each.

**Deadline:** 30.09.2019 - 23.59

**Comment by sercanersoy** [comment]
> > In scenario 6, i just wonder is the alert for buying or selling price because there is a gap between them and I usually set different alerts for each.
> 
> Changed the text in [Scenario 6](https://github.com/bounswe/bounswe2019group8/wiki/Mockups#scenario-6-salih-okutan) a little bit to clarify the transaction.

@furkanaydar changed the text of scenario 6. Writing it here in order the close other issue #111.

**Comment by furkanaydar** [comment]
Explained the alert in Scenario 6, in more detail. Action 4 is done.

**Comment by cerentahtasiz** [comment]
I also agree that search by price button is not necessary. I changed the mock-up picture in scenario 2. Action 2 is done.

**Comment by alpercakan** [comment]
Please add any questions you might want to ask the customer here:
https://github.com/bounswe/bounswe2019group8/wiki/Questions-for-the-Customer-Meeting-on-30-09-2019

**Comment by sercanersoy** [comment]
Action 1 is checked because there is a mockup for signing up in web. The functionality will be same in mobile, too.

**Comment by sercanersoy** [comment]
New issue is created (see #119). Closing this issue.
