### ISSUE TITLE
Clarifying the Guest Access to User Portfolios

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#116]
**Actions:**
1. Clarify, by scrutinizing the project document and/or contacting the customer, whether the guest users should be able to access the user portfolios.
1. Update the requirment document accordingly.

**Notes:**
1. See #114 

**Deadline:** 30.09.2019 - 22.00

**Comment by alpercakan** [comment]
From the project description (emphasis mine):

> User profiles can be **either public or private to the other users**. In order to see the contents
in a private user profile, user (with the private profile) should be followed. Also, each users
prediction success rate should be visible in their profile page.

This made me conclude that the guests should not be allowed to view the user portofolios. But I suggest that we ask the customer about this. Will bring this up during the customer meeting tomorrow, if this doesn't get any objections until then.

**Comment by alpercakan** [comment]
Asked the customer about this. Waiting his response.

**Comment by yilmazvolkan** [comment]
We discuss with the customer and get response that the guest user should not see user portfolio.
