### ISSUE TITLE
Initialize the Backend

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#121]
**Actions:**
1. Initialize the backend with the team using Spring and MongoDB.
2. Decide coding conventions with the team.
3. Add decided conventions to CONTRIBUTING.md.

**Deadline:** 08.10.2019 - 13.00

**Comment by furkanaydar** [comment]
Backend is initialized. See branch [*backend/issue-121*](https://github.com/bounswe/bounswe2019group8/tree/backend/issue-121/backend)
Also, notes on initialized project: [here](https://github.com/bounswe/bounswe2019group8/blob/backend/issue-121/backend/README.md).
