### ISSUE TITLE
Initialize the Frontend

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#122]
- [x] **Initialize the frontend with the team using React.** 

- [x] **Decide coding conventions with the team.**

- [x] **Add decided conventions to CONTRIBUTING.md.**

**Deadline:** 08.10.2019 - 13.00

**Comment by efe-onal-2016400267** [comment]
We met and researched .jsx coding standards on GitHub. We liked the standards of Airbnb team, and decided to use the same convention.
