### ISSUE TITLE
Review the backend project

### ISSUE THREAD

**Issue by furkanaydar** [bounswe/bounswe2019group8#124]
**Actions:**
1. Review the initialized version of backend project.
2. Comment on the necessity of a potential tech stack change.

**Deadline:** 7.10.2019 - 21.00

**Comment by furkanaydar** [comment]
See [pull request ](https://github.com/bounswe/bounswe2019group8/pull/126 ).

**Comment by sercanersoy** [comment]
In the project dashboard, this issue and PR both shows. There are also columns for review status, we can track the process there. Thus, closing this issue.
