### ISSUE TITLE
Design the database model

### ISSUE THREAD

**Issue by furkanaydar** [bounswe/bounswe2019group8#125]
**Actions:**
1. Develop currently existing User model in database. Specify required fields for an User object.
2. Design models, collections and relations according to the upcoming milestone requirements.
3. Create a document explaining the results of **1** and **2**

**Deadline:** 12.10.2019 - 21.00

**Comment by ismet-dagli** [comment]
@furkanaydar @alpercakan @sercanersoy @ismet-dagli 

We(database team) met on 09.10.2019 and we decided what we will implement in the database until milestone 1.  This schema will be updated for milestone 2 and the final version of the project.  

![database_schema](https://user-images.githubusercontent.com/21147014/66758522-18879a80-eea7-11e9-9106-6b76dd32f549.png)
