### ISSUE TITLE
A better branch naming convention

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#127]
**Actions:**
1. Deciding whether we stick with the current convention or use the one proposed below.

**Notes:**
1. Currently, we are naming the branches as "{branch-directory}/issue-{number}". I think it will be hard to navigate the history once we have so many branches, as this name is uninformative until you actually go look up the issue itself. I think we should use informative names that describes what the branch does in a couple of words. Optionally, it can still contain the issue number. (In any case, I believe it is unnecessary to repeat the word "issue" in every branch name, we can just go with the number.)

**Deadline:** 09.10.2019

**Comment by sercanersoy** [comment]
The current one was only about branch naming but I agree with you in that we should have a proper PR naming convention. Branch naming and Git workflow will be discussed in the following meeting.

**Comment by alpercakan** [comment]
Sorry, I actually meant the branches. They should have informative names instead of issue numbers to help the navigation easier.

**Comment by sercanersoy** [comment]
We decided which Git workflow to use, so closing this issue. (See #134)
