### ISSUE TITLE
Initial API design

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#128]
**Actions:**
1. Design the intial version of the API, with a minimal yet useful number of endpoints.

**Notes:**
1. We should design the initial version of the API (after we are done with #125) by choosing the paths (/users, /health etc.) and deciding on their response formats/structures.

**Deadline:** 10.10.2019

**Comment by alpercakan** [comment]
@cerentahtasiz @yilmazvolkan 

By the way, I suggest you take a look at the Retrofit library for consuming (calling) the API.

**Comment by sercanersoy** [comment]
Initial API design is decided. Closing this issue.
