### ISSUE TITLE
Decide visual standards

### ISSUE THREAD

**Issue by baris-zongur-2016400285** [bounswe/bounswe2019group8#132]
**Actions:**
1. DIscuss UI spesifications such that web and mobile pages looks correlated.

**Deadline:** 12.10.2019 - 00.00

**Comment by cerentahtasiz** [comment]
Web team, can you share your color code? We used this blue tone for mobile: #2E8BC0

**Comment by ozdenali** [comment]
We used:

- #f8f9fa for navigation bar
- #dc3545 for sign up button
- #28a745 for login button
- #007bff for form submit buttons
- #0069d9 for form submit buttons (on hover)

**Comment by yilmazvolkan** [comment]
We decided visual standards in our applications.
