### ISSUE TITLE
Revise the requirements page in wiki

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#135]
**Actions:**
1. Revise the requirements for upgrading from basic user to a trader.
1. Revise the requirements for downgrading from trader to a basic user.
1. Revise the requirements for notifications.
1. Revise the requirements for guest users accesses.

**Notes:**
- [x] Action 1
- [x] Action 2
- [x] Action 3
- [x] Action 4

**Deadline:** 13.10.2019 - 23.59

**Comment by alpercakan** [comment]
We should also revise the non functional requirements
