### ISSUE TITLE
Decide application name

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#136]
**Actions:**
1. Members write their name ideas under this issue.
2. Choose application name according to the idea of the majority.

**Deadline:** 16.10.2019

**Comment by alpercakan** [comment]
Mercatus

**Comment by cerentahtasiz** [comment]
I found a webpage which creates brand name and logo. You can check for inspiration. If we use one of these, it saves us time for logo. https://namelix.com

**Comment by cerentahtasiz** [comment]
I just realized, it is also important that we can find a similar and cheap domain name

**Comment by sercanersoy** [comment]
I checked for available domains for the name mercatus. Extensions ```com```, ```org```, ```io``` and ```tech``` are taken. Extension ```net``` costs 13652₺.

Available and affordable ones that were appealing:
- ```mercatus.xyz``` -> 5,81₺
- ```mercatus.dev``` -> 74,99₺

**Comment by sercanersoy** [comment]
**Mercatus** is chosen. Closing this issue.
