### ISSUE TITLE
Move POST request content type from url encoded to json

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#137]
**Actions:**
1. Currently, ```POST``` request data has ```application/x-www-form-urlencoded``` as their content-type. Content-type will be changed to ```application/json``` to stick to REST convention.

**Deadline:** 12.10.2019 - 23.59

**Comment by furkanaydar** [comment]
Related [pull request](https://github.com/bounswe/bounswe2019group8/pull/138) is merged, closing.
