### ISSUE TITLE
Migrate to the PostGre

### ISSUE THREAD

**Issue by furkanaydar** [bounswe/bounswe2019group8#139]
**Actions:**
1. Migrating to PostgreSQL. Reconfiguring affected classes.
2. Reconfiguring the security. 
3. Adding /follow and /unfollow endpoints

**Notes:**
1. We decided that Mongo lacks some features that we will be using repeatedly (such as cascading deletes). Also team concluded that thinking relational would help our implementations.
2. One type of authority is enough for authentication process. (i.e 'admin' should not need to be also a 'trader')

**Deadline:** 12.10.2019 - 15.00

**Comment by sercanersoy** [comment]
Closing this old issue.
