### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#145]
**Actions:**
1. Document the API endpoints along with their expected params and responses.

**Notes:**
1. I suggest using Postman's collection sharing feature, which automatically creates a docs page and on top of that it makes it really easy to reproduce the example API calls in Postman for manual testing.

I had already used this feature for the practive app in the last semester: see https://documenter.getpostman.com/view/2365580/S1LySmQB?version=latest

**Deadline:** 15.10.2019

**Comment by sercanersoy** [comment]
See [API Docs](https://documenter.getpostman.com/view/8736871/SVzuZgBL?version=latest). Closing this issue.
