### ISSUE TITLE
Requirements Again According to Feedback!

### ISSUE THREAD

**Issue by efe-onal-2016400267** [bounswe/bounswe2019group8#16]
Actions:

1. Everyone revise your part Requirements Document according to the feedback we received on Tuesday.

**Deadline: 3.3.2019**
**Depends on:** #12

**Comment by yusufyuksel96** [comment]
done.

**Comment by furkanaydar** [comment]
done

**Comment by ozdenali** [comment]
done with @sercanersoy

**Comment by alpercakan** [comment]
done

**Comment by efe-onal-2016400267** [comment]
done
