### ISSUE TITLE
Render Login and Signup Routers Within the Index Page

### ISSUE THREAD

**Issue by efe-onal-2016400267** [bounswe/bounswe2019group8#162]
**Actions:**
1. Login and Signup forms should be rendered within the root component.

**Notes:**
1. Right now when Login or Signup buttons are clicked, the whole page is rerendered. This shouldn't be the case.

**Deadline:** 18.10.2019 - 21.43 (date is always required, whereas the time part is optional and if needed, should be shown it like this.)

**Comment by baris-zongur-2016400285** [comment]
Done
