### ISSUE TITLE
Develop Edit user profile screen

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#187]
**Actions:**
1. Add edit user location to user profile.
1. Add edit user name and surname and other fields.
1. Update user info with backend.
1. Design a layout when user wants to edit only 1 field.

**Notes:**
- [ ] Add edit user location to user profile.
- [x] Add edit user name and surname and other fields.
- [x] Update user info with backend.
- [x] Design a layout when user wants to edit only 1 field.

**Deadline:** 01.11.2019 - 23.59

**Comment by yilmazvolkan** [comment]
I created a layout to easily edit user profile. Since Google maps is not integrated yet, change location should be added when it is available. You can see more details from [here](https://github.com/bounswe/bounswe2019group8/pull/234/commits/841a930287bf199d514e1354e3f0961c58f038ea)

**Comment by ismet-dagli** [comment]
One more action:
5- Changing password functionality is added. It is added a few merges ago.

Correction on action2: user name and surname will remain constant and other fields are changeable.

**Comment by ismet-dagli** [comment]
It is done #243
