### ISSUE TITLE
Develop small features for mobile

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#188]
**Actions:**
1. Add logout functionality.
1. Fix when you click back button on Android, it logouts and exists the app.
1. Enhance register page screen visuality.
1. Add sidebar for settings, show my profile sections. You can see more [here](https://blog.mindorks.com/android-navigation-drawer-in-kotlin)

**Notes:**
- [x] Add logout functionality.
- [x] Fix when you click back button on Android, it logouts and exists the app.
- [x] Enhance register page screen visuality.
- [x] Add sidebar for settings, show my profile sections. 

**Deadline:** 01.11.2019 - 23.59

**Comment by yilmazvolkan** [comment]
Helped register page screen improvement and navigation bar addition.

**Comment by yilmazvolkan** [comment]
Navigation bar functinality somehow does not right, added click events and updated fragments.

**Comment by ismet-dagli** [comment]
Actions are done piece by piece on different commits but done with the help of @yilmazvolkan.
