### ISSUE TITLE
Research about GitHub & Git

### ISSUE THREAD

**Issue by baris-zongur-2016400285** [bounswe/bounswe2019group8#2]
**Actions**:

1. Explore GitHub repositories to discover repos that you like. 
2. Document them in the [Wiki page](https://github.com/bounswe/bounswe2019group8/wiki/GitHub-&-Git-Research) by giving their links and describing what you liked.
3. Using the outcomes of the research, create a short summary about the features of GitHub and git that sound significant and useful.

**Deadline** : 17.02.2019

**Comment by yusufyuksel96** [comment]
Done

**Comment by alpercakan** [comment]
Done

**Comment by baris-zongur-2016400285** [comment]
Done

**Comment by cerentahtasiz** [comment]
done

**Comment by ozdenali** [comment]
Done
