### ISSUE TITLE
Create Articles Page

### ISSUE THREAD

**Issue by ismet-dagli** [bounswe/bounswe2019group8#209]
**Actions:**
1. Add go articles shortcut in navigation bar and and
1. Create an article functionality
1. Show list of articles on the screen(feed).
1. Create article.

**Notes:**
- [x] Add go articles shortcut
- [x] Show list of articles.
- [ ] Create articles.

**Deadline:** 19.11.2019 - 23.59

**Comment by yilmazvolkan** [comment]
Articles feed is created and navigation setup is successful.

**Comment by yilmazvolkan** [comment]
Create articles added successfully. You can see more detals from [here](https://github.com/bounswe/bounswe2019group8/pull/231)
