### ISSUE TITLE
Add comments on Articles

### ISSUE THREAD

**Issue by ismet-dagli** [bounswe/bounswe2019group8#210]
**Actions:**
1. Add comments on articles functionality
1. Show list of comments below articles
1. Edit comments below articles
1. Delete comments below articles
1. Navigate users from comments.

**Notes:**
- [x] Add comment
- [x] Show comments
- [x] Delete comment
- [x] Edit comments
- [x] Navigate users from comments.

**Deadline:** 21.11.2019 - 23.59

**Comment by yilmazvolkan** [comment]
After discussion, i take this part to implement.

**Comment by yilmazvolkan** [comment]
You can see more details from [here](https://github.com/bounswe/bounswe2019group8/pull/234)
