### ISSUE TITLE
Create Events

### ISSUE THREAD

**Issue by ismet-dagli** [bounswe/bounswe2019group8#211]
**Actions:**
1. Add go events shortcut in navigation bar
1. Add button in order to create event
1. Enter the details of event
1. Create an event
**Notes:**
- [ ] Add go events shortcut in navigation bar.
- [ ] Implement list of events show screen.
- [ ] Connect with the backend to get events.

**Deadline:** 19.11.2019 - 23.59

**Comment by yilmazvolkan** [comment]
Since backend is not implemented and deployed, new deadline is 26.11.2019

**Comment by ismet-dagli** [comment]
Done in #283, you can see the details in [here](https://github.com/bounswe/bounswe2019group8/pull/283)
