### ISSUE TITLE
Deciding on Recurring Jobs Mechanism

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#218]
**Actions:**
1. Decide on how we handle recurring jobs in the backend app.

**Notes:**
1. We need to find a way to schedule the recurring tasks, such as retrieving the latest financial data from the external APIs,

**Deadline:** 16.11.2019

**Comment by alpercakan** [comment]
We can either use a recurring task library, or we can just use cron jobs. I think that it will be easier to use the following design: 

We create an admin user for the recurring jobs, and implement some internal endpoints that can be called only by the admin users. Then, we create cron jobs that regularly login as this admin user and call the endpoint. The main advantages of this method are that it is way easier that using an external library, and that we can easily force-update the financial data before the scheduled time simply by logging as an admin and calling the required endpoint.

**Comment by furkanaydar** [comment]
Our parities and events are being updated automatically now. Closing

**Comment by alpercakan** [comment]
We decided to use cronjobs and curl requests.
