### ISSUE TITLE
.

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#240]
**Actions:**
1. Enumerate actions and notes like this.
1. Use a single imperative sentence in each item, deferring any long details to the notes section below.
1. Follow the usual punctuation and capitalization rules; such as starting the sentencences and names with a capital letter, ending the sentence with a proper punctuation mark and so on.
1. Assign at least one person.
1. Add the labels (e.g. priority, estimated level of effort) to make planning and organizing the issues easier.
1. Specify the deadline.

**Notes:**
1. Notes part is optional but if there are things that must be specified, list them here like this.
1. Temporarily assign yourself until you can find someone willing to take over the issue.
- [ ] For action 1: You can add details for specified action like this.
- [ ] You can also use to-do lists like this.

**Deadline:** 18.10.2019 - 21.43 (date is always required, whereas the time part is optional and if needed, should be shown it like this.)

**Comment by sercanersoy** [comment]
Assuming this issue is opened accidentally and closing it. If not, it can be reopened.
