### ISSUE TITLE
Trading Equipment Search

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#258]
**Actions:**
1. Create floating actions buttons through each trading equipment fragments'.
1. Create search screen for trading equipments.
1. Connect these fragments with the same search screen via click event.
1. Create trading item to print search result.
1. Connect with the backend.

**Notes:**
- [ ] Create floating actions buttons through each trading equipment fragments'.
- [ ] Create search screen for trading equipments.
- [ ] Connect these fragments with the same search screen via click event.
- [ ] Create trading item to print search result.
- [ ] Connect with the backend.

**Deadline:** 25.10.2019 - 23.43

**Comment by ismet-dagli** [comment]
Done in #283, you can see the details in [here](https://github.com/bounswe/bounswe2019group8/pull/283)
