### ISSUE TITLE
Individual  Photo Upload

### ISSUE THREAD

**Issue by yusufyuksel96** [bounswe/bounswe2019group8#27]
**Action**: 
1.Upload your individual photos.

**Deadline**: 10.03.2019

**Comment by sercanersoy** [comment]
Upload your individual photo to following directory in the repository:
- images/individual-photos
Also, it would be nice if you use lowercase letters and '-' instead of white space.

**Comment by sercanersoy** [comment]
done

**Comment by alpercakan** [comment]
We should also use the indiviual photos in the readme page (in a tabular form with the names maybe, as some of the groups from previous years did) and in the personal pages.

**Comment by ahmetyigitgedik** [comment]
done!

**Comment by alpercakan** [comment]
done

**Comment by yusufyuksel96** [comment]
done

**Comment by cerentahtasiz** [comment]
done
