### ISSUE TITLE
Making a Class Diagram

### ISSUE THREAD

**Issue by ahmetyigitgedik** [bounswe/bounswe2019group8#29]
**Actions:**
1. Discuss about how to make a class diagram and create it.

**Deadline:** 10.03.2019, 23:59

**Comment by sercanersoy** [comment]
[Class Diagram Link](https://www.lucidchart.com/invitations/accept/4b5c85d7-d199-4e9f-b6f6-48cf07521197)

**Comment by ahmetyigitgedik** [comment]
Done

**Comment by alpercakan** [comment]
I should add an InvestmentController

**Comment by alpercakan** [comment]
By the way, see #45. It can of incredible help.

**Comment by sercanersoy** [comment]
Closing this issue now. Further improvements to the class diagram can be discussed under #43 .
