### ISSUE TITLE
Prepare Agenda for Meeting 3

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#3]
**Actions**:

1. Prepare the agenda for the third weekly meeting, according to the assignment given on monday.

**Deadline** : 24.02.2019, 23:59

**Comment by cerentahtasiz** [comment]
note: https://github.com/bounswe/bounswe2019group8/issues/8#issuecomment-466798958

**Comment by cerentahtasiz** [comment]
note: https://github.com/bounswe/bounswe2019group8/issues/11

**Comment by alpercakan** [comment]
note: #12

**Comment by cerentahtasiz** [comment]
note: https://github.com/bounswe/bounswe2019group8/issues/14

**Comment by ahmetyigitgedik** [comment]
thanks for ideas! I will add them to the agenda.@cerentahtasiz @alpercakan
