### ISSUE TITLE
Implementing commodity prices fetcher

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#308]
**Actions:**
1. Implement the internal endpoint for fetching the commodity prices from NASDAQ.

**Notes:**
1. NASDAQ API can be used for this purpose. See an example endpoint:
https://api.nasdaq.com/api/quote/GC:CMX/chart?assetclass=commodities&fromdate=2019-11-01&todate=2019-11-30

It returns only the daily close values.

**Deadline:** 15.12.2019

**Comment by sercanersoy** [comment]
Historical api can be used for daily open, close, low, high prices:
https://api.nasdaq.com/api/quote/GC%3ACMX/historical?assetclass=commodities&fromdate=2019-11-11&limit=30&todate=2019-12-11
