### ISSUE TITLE
Organize the Notes of Week 4 PS

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#31]
**Actions**:

1. We should collect all notes we have taken during today's PS and organize them:
    So that we can refer to it while we are preparing the use case diagrams, class diagrams and sequence diagrams.

**Deadline** : 07.03.2019

**Comment by cerentahtasiz** [comment]
I'm done with my part @alpercakan

**Comment by alpercakan** [comment]
Done
