### ISSUE TITLE
More Detailed and Consistent Backgrounds for Personae

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#38]
**Actions**:
1. Add more substance to the backgrounds of the personae.
2. Use the people's name in the user stories and background texts (for example, refer by "İlayda" instead of "the trader")
3. Fix the location inconsistencies (some people have locations both as Bakırköy and the north campus dorm in the mockup flows).

**Comment by sercanersoy** [comment]
Is this done?

**Comment by alpercakan** [comment]
Yeah it seems that it is
