### ISSUE TITLE
Portfolio Improvement

### ISSUE THREAD

**Issue by yilmazvolkan** [bounswe/bounswe2019group8#416]
**Actions:**
1. Fix bugs inside portfolio section.
1. Develop better visual layouts. 
1. Connect with backend.

**Notes:**
- [x] Fix bugs inside portfolio section.
- [x] Develop better visual layouts. 
- [x] Connect with backend.

**Deadline:** 24.10.2019 - 18.43

**Comment by ismet-dagli** [comment]
Done #421
