### ISSUE TITLE
Review the Class Diagrams

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#43]
**Actions:**
1. Everyone should go over the class diagrams and leave feedbacks so that we can finalize them before working on the sequence diagrams.

**Deadline:** 15.03.2019, 10.00

**Comment by alpercakan** [comment]
I think we have to show the parameters (with types and names) and the return types of the methods in the class diagram. This change might also affect the corresponding sequence diagrams.

**Comment by sercanersoy** [comment]
done
