### ISSUE TITLE
Splitting of Mockups and Adding New Stories

### ISSUE THREAD

**Issue by ahmetyigitgedik** [bounswe/bounswe2019group8#44]
**Actions**
1. Split each mockup by considering informations written below and add new stories. 

**Ahmet Kazan**
1. Sign up via Google
2. My investments
3. Buy order
4. Set alert for equipment

**Salih**
1. Sign-up
2. Find a political event - set alert for an event
3. Invest

**Taylan Aksoy**
1. Searches people -Filtering by prediction rate- Fallow another user.
2. Receive notifications about article- read & rate article 

**İlayda**
1. Login 
2. Search trading equipment(filtered by price) - follow an equipment.
3. Observes the equipment in portfolio.

**Comment by sercanersoy** [comment]
done (for taylan)

**Comment by alpercakan** [comment]
Done for Ahmet

**Comment by alpercakan** [comment]
We have split them.
