### ISSUE TITLE
Draw Sequence Diagrams

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#51]
**Actions:**
1. Drawing the sequence diagrams for each of the _significant_ use cases.

_Will update with the indiviual use case assignments_

**Deadline:** 18.03.2019, 09.00

**Comment by alpercakan** [comment]
You should keep the editable diagram/drawing. See https://github.com/bounswe/bounswe2019group8/issues/43#issuecomment-473689150_

**Comment by alpercakan** [comment]
Done

**Comment by furkanaydar** [comment]
Done (Semantic search, economic event search)

**Comment by sercanersoy** [comment]
I renewed the class diagram and sequence diagrams for rate article and write article. Also added links for editing them. Please adhere to convention in sequence diagrams.

**Comment by furkanaydar** [comment]
Search sequence diagrams are updated according to the new Class diagram.

**Comment by alpercakan** [comment]
Seems to be done
