### ISSUE TITLE
Changed Use Case Diagram According to Feed Back

### ISSUE THREAD

**Issue by efe-onal-2016400267** [bounswe/bounswe2019group8#52]
**Actions:**
1. I've made necessary changes on Use Case Diagram, you can check it and if you like, change it. 

**Deadline:** 23.03.2019

**Comment by efe-onal-2016400267** [comment]
https://www.lucidchart.com/invitations/accept/fc05d1db-695d-47cb-9e8c-fe0f92543377
to see on lucid chart.

**Comment by uskudarli** [comment]
@efe-onal-2016400267 who is "you" ? It is good to assign tasks to people. 

There are no assignee's for this task.

**Comment by efe-onal-2016400267** [comment]
Right, sure.
