### ISSUE TITLE
Post the Final Class Diagram

### ISSUE THREAD

**Issue by efe-onal-2016400267** [bounswe/bounswe2019group8#53]
**Actions:**

1.  I've made some minor changes to the class diagram. It seems like we are all going to have to make some changes. It would be nice if we posted it on the Class Diagram page after the last update. 

**Deadline:** 24.03.2019, 23.59

**Comment by efe-onal-2016400267** [comment]
Note: the link on the Class Diagram page is an edit link.

**Comment by alpercakan** [comment]
Done
