### ISSUE TITLE
Milestone Report (Evaluation and Individual Work)

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#57]
Actions:

* Evaluation of the ​status​ of deliverables and its impact on the project plan will be added by everyone who are responsible for that deliverable. 
* A summary of work done by each team member will be added individually.

Deadline: 1.04.2019, 23.59

**Comment by cerentahtasiz** [comment]
personas and project documents are evaluated, done for me

**Comment by alpercakan** [comment]
Evaluation of the sequence diagrams is  ✅

**Comment by alpercakan** [comment]
Done
