### ISSUE TITLE
User Requirements Part of Requirements Document

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#6]
**Actions**:

1. Prepare the user requirements part of requirements document considering the PS on friday.
2. Update requirements document on Wiki.
2. Prepare questions regarding this part and update questions document on Wiki.

**Deadline** : 24.02.2019, 23:59

**Comment by efe-onal-2016400267** [comment]
Hey guys,
I prepared a simple classification about the user requirement but there are parts that I am not sure about. Should we discuss them on  Skype? I also prepared some questions on the parts of the description that seemed to need clarification.

**Comment by alpercakan** [comment]
Hey,

Maybe you can just propose your classification method here. Once we complete our part, we'll need to reorganize it anyways to create the whole document by merging with other parts (#4, #5, #7). So, we will then have time to discuss the organization of the whole document.

I guess the same also goes for the questions: we'll have to put them in a single document before contacting the customer. So, maybe you can just shoot them here (and also perhaps we can resolve some of them together).

**Comment by alpercakan** [comment]
By the way, the following links contain some, in my opinion, good examples of the document organization/structure:

1. http://web.cse.ohio-state.edu/~bair.41/616/Project/Example_Document/Req_Doc_Example.html
2. https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis

**Comment by efe-onal-2016400267** [comment]
Ok, here is the first classification then:  
[User-Requirements-First-Classific.txt](https://github.com/bounswe/bounswe2019group8/files/2897775/User-Requirements-First-Classific.txt)

**Comment by cerentahtasiz** [comment]
@efe-onal-2016400267 I think it might be better if you put all those specifications on related Wiki docs so we can see all updates and specifications more conveniently.
