### ISSUE TITLE
Labor Division of Past Tasks in Project Plan

### ISSUE THREAD

**Issue by yusufyuksel96** [bounswe/bounswe2019group8#61]
**Description**:

1.Past tasks in project plan will  divide among assignees.

**Deadline**: 05.04.2019 23:59

**Comment by alpercakan** [comment]
Since there have been roughly eight weeks, we can assign two weeks to each person.
I'm starting with week 1 and week 2.

**Comment by alpercakan** [comment]
After sharing the weeks/tasks, please everbody add their part to the following spreadsheet:
https://docs.google.com/spreadsheets/d/1uAEQKscOW-A5xCJSDJFi7L_jL5xMT083jKjM7j1UCQE/edit?usp=sharing

Ideally, we should work togethor on the Project Libre platform. However, it seems that there is a problem about the registration on their platform. So, I guess the best solution now is to start with a draft using the spreadsheet, and after we're done, one of us can create the pod file according to the spreadsheet.

**Comment by alpercakan** [comment]
Also, please be careful about grouping the tasks. Granted, it won't be easy enough doing that in the spreadsheet as it would be if we were using the Libre directly; but I suppose we can just use the columns for indentation (to denote the subgroups).

Example: If you are writing the subtasks for project requirements, write "project requirements" in the column A and write "preparing a glossary" in the column B.

**Comment by alpercakan** [comment]
See https://github.com/bounswe/bounswe2019group8/issues/64#issuecomment-480619565
