### ISSUE TITLE
Deciding Work Split About Future Tasks in Project Plan Assignment

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#62]
**Description:**

Assignees will decide what do do next and fill project plan accordingly. They will split the work among themselves about how to fill project plan table.

**Actions:**
1. Assignees will discuss about what to do next about the project and fill the project plan accordingly
2. They will split the work about filling the project plan table of future works among themselves

**Deadline:** 05.04.2019 23.59

**Comment by alpercakan** [comment]
Please see https://github.com/bounswe/bounswe2019group8/issues/61#issuecomment-480614508

**Comment by alpercakan** [comment]
Also see https://github.com/bounswe/bounswe2019group8/issues/61#issuecomment-480614802

**Comment by alpercakan** [comment]
See https://github.com/bounswe/bounswe2019group8/issues/64#issuecomment-480619565
