### ISSUE TITLE
Merging the Weekly Plans

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#64]
**Actions:**
1. Merging the [weekly plans](https://docs.google.com/spreadsheets/d/1uAEQKscOW-A5xCJSDJFi7L_jL5xMT083jKjM7j1UCQE/edit?usp=sharing) we prepared into a single Project Libre file.

**Deadline:** 08.04.2019 09.00

**Comment by alpercakan** [comment]
Please complete your weekly parts as soon as possible so that I will be able to merge them before the deadline. @bounswe/bounswe2019group8

**Comment by alpercakan** [comment]
Please complete your weekly parts as soon as possible so that I will be able to merge them before the deadline.

**Comment by alpercakan** [comment]
Reminder: Review the following document as a reference
https://github.com/bounswe/bounswe2018group5/wiki/Project-Plan

**Comment by alpercakan** [comment]
For each task, you should specify:
- Name
- Start date
- Finish date (time and date) or duration (days)
- Predecessors (see below "Dependencies")
- Resource Names (ie, the people who did that task, assignees)

Read the section "standard types of dependencies" on [Dependency (Wikipedia article)](https://en.wikipedia.org/wiki/Dependency_(project_management)) for details about dependencies.

**Comment by alpercakan** [comment]
It seems that no one else has done their part. I have added my part (first two weeks' plans) to a .pod (Project Libre) [file](https://github.com/bounswe/bounswe2019group8/blob/master/deliverables/Project_Plan.pod), please continue from there (I also uploaded its [pdf version](https://github.com/bounswe/bounswe2019group8/blob/master/deliverables/Project_Plan.pdf)). Since obviously I cannot wait indefinitely, I am unassigning myself, and everyone should add their part on top of this .pod file.

**Comment by alpercakan** [comment]
I completed all weeks' plans, merged them and uploaded them, all on my own. I think in a group of ten people a single should not have to do all of the weekly work; I hope all team members abide by the deadlines for the next tasks and this does not happen again.

**Comment by efe-onal-2016400267** [comment]
You posted these before the deadline. I had set an alarm before the deadline and woke up. Then I saw this.

**Comment by alpercakan** [comment]
I prepared all of the weekly plans, merged them and uploaded them.
