### ISSUE TITLE
Research for Assignment 7

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#67]
**Actions:**

1. We should make a research on API, git versioning system, RESTful API. One of the resource is the examples shared by professor on Piazza.

**Deadline:** 18.04.2019 23.59

**Comment by alpercakan** [comment]
Please see some of the examples below to get an idea about APIs and how to use:

- [Stripe](https://stripe.com/docs/api?lang=python)
- [İş Bank](https://developer.isbank.com.tr/Pages/branches-api.aspx)
- [Yapı Kredi](https://apiportal.yapikredi.com.tr/apiresources/explorer)

I mainly posted financial ones, but feel free to do more research and post some examples below.

**Comment by cerentahtasiz** [comment]
These are the links provided in assignment page by the professor, check them out:

Useful Links:
• Review: https://github.com/blog/2123-more-code-review-tools
• Pull request: https://help.github.com/articles/about-pull-request-reviews/
• Developing API: https://apiblueprint.org, http://swagger.io, http://raml.org/
• Testing API/RESTClient: https://www.getpostman.com, http://alternativeto.net/software/httprequester

**Comment by alpercakan** [comment]
Small example to help you better understand what we need to do:

Say we chose to use an API which provides stock prices. Then, we can implement, for example, the following API functionalities:
- An endpoint that returns the 5 day moving average for a particular stock (we'll use the 3rd party API to get the price of that stock for the last 5 days, and rest is just simple algebra)
- An endpoint that allows you to buy a specified amount of lots (pieces) of that stock (if you have enough balance in your account; so, again we need the fetch the current price from the 3rd party API)

As you can see, we'll implement a functionality that can be useful for our actual project next semester, and while doing so, we need to use a 3rd party API.

**Comment by alpercakan** [comment]
We have completed the implementation assignment.
