### ISSUE TITLE
Choosing the API to be Used

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#68]
**Actions:**

1. Choose the API that we will use for the assignment 7. See below for details.

**Deadline:** 18.04.2019 23.59

**Comment by alpercakan** [comment]
We need to choose an API that we can use for the actual project next semester. Of course, one of the first options that came to my mind was investing.com, but unfortunately they do not have an API.

**Comment by sercanersoy** [comment]
API for stock prices: [Alpha Vantage](https://www.alphavantage.co/documentation/)

We can use above 3rd party API to get daily, weekly, monthly or intraday values of the currencies and stock prices. It also offers keyword search among the currencies and stocks.

In addition to what @alpercakan suggested in #67 (moving avg and buy order API) I suggest implementing a basic search endpoint with a simple UI. It is essential for "search trading equipments" property in the project.

**Comment by sercanersoy** [comment]
API for buy or sell order executions: [TradeStation](https://tradestation.github.io/api-docs/)

Can be used or what @alpercakan said in #67.
