### ISSUE TITLE
Assignment 7 is to be Added to Project Plan

### ISSUE THREAD

**Issue by efe-onal-2016400267** [bounswe/bounswe2019group8#69]
**Actions:**
1. Work related to assignment 7 is to be added to the Project Plan.

**Deadline: 21.5.2019**

**Comment by alpercakan** [comment]
What is the current status of this issue? The implementation assignment has to be added to the project plan for the milestone 2, whose deadline is tomorrow.

**Comment by cerentahtasiz** [comment]
any updates? @baris-zongur-2016400285

**Comment by baris-zongur-2016400285** [comment]
doing right now

**Comment by baris-zongur-2016400285** [comment]
done
