### ISSUE TITLE
System Requirements Part of Requirements Document

### ISSUE THREAD

**Issue by cerentahtasiz** [bounswe/bounswe2019group8#7]
**Actions**:

1. Prepare the system requirements part of requirements document considering the PS on friday.
2. Update requirements document on Wiki.
2. Prepare questions regarding this part and update questions document on Wiki.

**Deadline** : 24.02.2019, 23:59

**Comment by cerentahtasiz** [comment]
I found a nice webpage on how to create system requirements document, you can check it out: https://existek.com/blog/how-to-write-the-system-requirements-specification-for-software-development/

**Comment by cerentahtasiz** [comment]
Done for me, but I accidentally wrote 'more user requirements with more details' instead of 'system requirements' on commit.

**Comment by ahmetyigitgedik** [comment]
Done!
