### ISSUE TITLE
Choosing Tech Stack

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#71]
**Actions:**
1. Choosing the frameworks, languages, DB etc. that we are going to use for the assignment.

**Deadline: 19.5.2019 23.59**

**Comment by alpercakan** [comment]
I suggest using Python+Flask for the backend since the size of the project is small and we have to be quick.

For the frontend, since we don't need anything shiny, we can just use basic HTML and JS (and plain old XHR for the API reqs).

To help everyone have a better idea of what we need to do, I will create the basic structure along with the first couple of endpoints as soon as possible (after we choose the 3rd party API we'll employ).

**Comment by sercanersoy** [comment]
Techs that we could use discussed after today's meeting:
- Backend: Python+Flask
- Frontend: HTML and JS
- Database: PostgreSQL

API for stock prices: [Alpha Vantage](https://www.alphavantage.co)
- Can be used to get daily, weekly, monthly or intraday values of the currencies. Also can be used for searching stock symbols (MSFT) and keywords (Microsoft).

API for Twitter: [Twitter API](https://developer.twitter.com/en/docs.html)
- We can retrieve user tweets on specific economic events and have users tweet their portfolio, articles or accomplishments.

API for stock price charts and economic events: [TradingView API](https://www.tradingview.com/tradingview-for-the-web/)
- Perfect for use in mobile and desktop applications, fin portals, blogs and news sites. It’s optimal when you want total control over your charting and want to show data that you control.

**Comment by alpercakan** [comment]
This looks grand, thank you! I'll create a new issue for this deciding which features/endpoints we'll implement ourselves using which features from these APIs.
