### ISSUE TITLE
Implement the Comment Create Endpoint

### ISSUE THREAD

**Issue by sercanersoy** [bounswe/bounswe2019group8#74]
**Actions:**

1. Implement the endpoint which creates a comment left about a trading equipment.

**Details:**

For example, when you send a HTTP POST request to "comments/msft", you should create a comment left about the Microsoft stocks.

**Deadline:** 04.05.2019 23.59

**Comment by alpercakan** [comment]
Can you create a PR with your implementation? ("backend" branch)

**Comment by sercanersoy** [comment]
Done
