### ISSUE TITLE
Better Issues and Labeling

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#8]
**Actions**:

1. Create new issue labels to help us track issues more easily
2. Create a couple of issue templates to avoid copy-pasting the format from previous issues

**Deadline** : 27.02.2019, 23:59

**Comment by alpercakan** [comment]
Some examples for the labels:

1. https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
2. https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

Personally, I liked the first one better: looks more organized & easier to navigate to me.

**Comment by alpercakan** [comment]
Help documents for creating issue templates:
1. https://help.github.com/en/articles/about-issue-and-pull-request-templates
2. https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Some example templates:
1. https://github.com/stevemao/github-issue-templates
2. https://github.com/devspace/awesome-github-templates
3. https://bl.ocks.org/auremoser/72803ba969d0e61ff070

Thankfully, GitHub supports mulltiple issue templates. So we can use different (although, it would be a plus if they looked similar) templates for different issue types.

**Comment by cerentahtasiz** [comment]
Can you add this to our agenda for 3rd meeting? @ahmetyigitgedik

**Comment by ahmetyigitgedik** [comment]
Sure! @cerentahtasiz

**Comment by alpercakan** [comment]
In light of the feedback given in the lecture today, I also suggest creating labels such as "Question", "Needs Clarification" so that we can easily track the questions we have for the customer here on GitHub.
