### ISSUE TITLE
Deploying the Application to AWS

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#83]
**Actions:**

1. Deploy our application to the AWS server.

**Deadline:** 06.05.2019 23.59

**Comment by alpercakan** [comment]
This is still available, someone should assign themselves.

**Comment by alpercakan** [comment]
@sercanersoy I just added (to the "frontend" branch) a new yarn command "serve",  it might be useful for the deployment.

**Comment by alpercakan** [comment]
By the way, we should remember to update the API base URL (it should be somewhere in the frontend app) to have it pointing to the IP of our AWS server.

**Comment by sercanersoy** [comment]
Our API (back-end Flask application) is now working on the AWS machine. [Click here](http://18.188.149.114:8080/) to see API homepage. I am working on front-end application currently

**Comment by sercanersoy** [comment]
Our front-end application is also working on the AWS machine. [Click here](http://18.188.149.114/) to see front-end app homepage, [click here](http://18.188.149.114/tr-eqs/msft) to see comments made on the Microsoft stock (msft). Closing this issue.

**Comment by alpercakan** [comment]
@sercanersoy  There have been some updates to the app, can you deploy the current version?
